//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_SEFE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class basvurusecilen
    {
        public int ID { get; set; }
        public string adsoyad { get; set; }
        public string dogumtarihi { get; set; }
        public string uyruk { get; set; }
        public string tc { get; set; }
        public string cinsiyet { get; set; }
        public string mail { get; set; }
        public string tel { get; set; }
        public string adres { get; set; }
        public string okul { get; set; }
        public string bolum { get; set; }
        public double notort { get; set; }
        public string stajzorun { get; set; }
        public string stajtur { get; set; }
        public int stajsure { get; set; }
        public string sgtrdurum { get; set; }
        public string refvar { get; set; }
        public string refadsoyad { get; set; }
        public string refbolum { get; set; }
        public string refmail { get; set; }
        public string reftel { get; set; }
        public string secilen { get; set; }
    
        public virtual basvuru basvuru { get; set; }
    }
}
