//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_SEFE.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class basvuru
    {
        public int ID { get; set; }

        [Required(ErrorMessage = "Ad soyad girin!")]
        public string adsoyad { get; set; }

        [Required(ErrorMessage = "Dogum tarihi girin!")]
        public string dogumtarihi { get; set; }

        [Required(ErrorMessage = "Uyruk girin!")]
        public string uyruk { get; set; }

        [Required(ErrorMessage = "Tc girin!")]
        public string tc { get; set; }

        [Required(ErrorMessage = "Cinsiyet girin!")]
        public string cinsiyet { get; set; }

        [Required(ErrorMessage = "Mail girin!")]
        public string mail { get; set; }

        [Required(ErrorMessage = "Tel girin!")]
        public string tel { get; set; }

        [Required(ErrorMessage = "Adres girin!")]
        public string adres { get; set; }

        [Required(ErrorMessage = "Okul girin!")]
        public string okul { get; set; }

        [Required(ErrorMessage = "Bölüm girin!")]
        public string bolum { get; set; }

        [Required(ErrorMessage = "Not ortalama girin!")]
        public double notort { get; set; }

        [Required(ErrorMessage = "Staj zorunluluk bilgisini girin!")]
        public string stajzorun { get; set; }

        [Required(ErrorMessage = "Staj türünü girin!")]
        public string stajtur { get; set; }

        [Required(ErrorMessage = "Staj süre girin!")]
        public int stajsure { get; set; }

        [Required(ErrorMessage = "Sigorta durum bilgisini girin!")]
        public string sgtrdurum { get; set; }

        [Required(ErrorMessage = "Referans bilgisini girin!")]
        public string refvar { get; set; }

        [Required(ErrorMessage = "Referans ad soyad girin!")]
        public string refadsoyad { get; set; }

        [Required(ErrorMessage = "Referans bölümünü girin!")]
        public string refbolum { get; set; }

        [Required(ErrorMessage = "Referans mailini girin!")]
        public string refmail { get; set; }

        [Required(ErrorMessage = "Referans telini girin!")]
        public string reftel { get; set; }
        public string secilen { get; set; }
    
        public virtual basvurusecilen basvurusecilen { get; set; }
    }
}
